# golangci-lint configuration v2
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional recommended linters
    - gocyclo
    - gosec
    - misspell
    - nolintlint
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - revive
          - unparam

  settings:
    gocyclo:
      min-complexity: 10
  
    misspell:
      locale: US
  
    revive:
      confidence: 0.8
  
    gosec:
      excludes:
        - G204 # Subprocess launched with variable - we use it for git commands

formatters:
  settings:
    gofmt:
      simplify: true
    
    goimports:
      local-prefixes: [github.com/codcod/repos]

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3
