repositories:
  - name: loan-pricing
    url: git@github.com:yourorg/loan-pricing.git
    tags: [java, backend]
    branch: develop
    path: cloned_repos/loan-pricing

  - name: web-ui
    url: git@github.com:yourorg/web-ui.git
    tags: [frontend, react]
    path: cloned_repos/web-ui
  
  - name: journey
    url: git@github.com:codcod/jira-epic-timeline.git
    tags:
      - python
      - sample
    path: cloned_repos/timeline