version: "1.0"

# Engine configuration
engine:
  max_concurrent_repos: 5
  repo_timeout: "10m"
  check_timeout: "2m"
  enable_progress_report: true
  enable_caching: true
  cache_ttl: "1h"

# Checker configurations
checkers:
  git-status:
    enabled: true
    timeout: "30s"
    options:
      check_uncommitted: true
      check_unpushed: true
  
  branch-protection:
    enabled: true
    timeout: "10s"
    options:
      require_reviews: true
      require_status_checks: true
  
  vulnerability-scan:
    enabled: true
    timeout: "5m"
    options:
      severity_threshold: "medium"
      include_dev_deps: false
  
  outdated-dependencies:
    enabled: true
    timeout: "1m"
    options:
      check_security: true
      check_major_versions: false

# Analyzer configurations
analyzers:
  javascript:
    enabled: true
    timeout: "5m"
    options:
      check_complexity: true
      max_complexity: 10
      include_tests: false
  
  python:
    enabled: true
    timeout: "5m"
    options:
      check_complexity: true
      max_complexity: 10
      check_style: true

# Reporter configurations
reporters:
  console:
    enabled: true
    format: "table"
    colors: true
  
  json:
    enabled: false
    output_file: "health-report.json"
    pretty_print: true
  
  markdown:
    enabled: false
    output_file: "health-report.md"
    include_summary: true

# Categories for organizing checks
categories:
  security:
    name: "Security"
    description: "Security-related checks"
    enabled: true
    severity: "high"
    weight: 1.5
    checkers:
      - branch-protection
      - vulnerability-scan
    options:
      fail_on_critical: true
  
  quality:
    name: "Code Quality"
    description: "Code quality and maintainability checks"
    enabled: true
    severity: "medium"
    weight: 1.0
    checkers:
      - outdated-dependencies
    options:
      threshold: 80
  
  git:
    name: "Git Management"
    description: "Git repository management checks"
    enabled: true
    severity: "low"
    weight: 0.5
    checkers:
      - git-status
    options:
      ignore_untracked: false

# Configuration profiles for different scenarios
profiles:
  development:
    name: "Development Profile"
    description: "Profile for development repositories"
    categories:
      - git
      - quality
    exclusions:
      - vulnerability-scan
    checkers:
      git-status:
        enabled: true
        options:
          check_uncommitted: false
      outdated-dependencies:
        enabled: true
        options:
          check_major_versions: true
  
  production:
    name: "Production Profile"
    description: "Profile for production repositories"
    categories:
      - security
      - quality
      - git
    checkers:
      vulnerability-scan:
        enabled: true
        options:
          severity_threshold: "low"
      branch-protection:
        enabled: true
        options:
          require_reviews: true
          require_status_checks: true
          require_signed_commits: true
  
  ci:
    name: "CI/CD Profile"
    description: "Profile for continuous integration"
    base: "production"
    categories:
      - security
      - quality
    exclusions:
      - git-status
    checkers:
      vulnerability-scan:
        timeout: "10m"

# Pipeline configurations
pipelines:
  default:
    name: "Default Health Check Pipeline"
    description: "Standard health check pipeline"
    steps:
      - name: "analysis"
        type: "analysis"
        enabled: true
        timeout: "5m"
        config:
          languages: ["javascript", "python", "go"]
          include_complexity: true
      
      - name: "security-checks"
        type: "checkers"
        enabled: true
        timeout: "10m"
        dependencies: ["analysis"]
        config:
          categories: ["security"]
          fail_fast: true
      
      - name: "quality-checks"
        type: "checkers"
        enabled: true
        timeout: "5m"
        dependencies: ["analysis"]
        config:
          categories: ["quality", "git"]
          continue_on_error: true
      
      - name: "reporting"
        type: "reporting"
        enabled: true
        timeout: "1m"
        dependencies: ["security-checks", "quality-checks"]
        config:
          formats: ["console", "json"]
          output_dir: "reports"
      
      - name: "validation"
        type: "validation"
        enabled: true
        timeout: "30s"
        dependencies: ["reporting"]
        config:
          min_score: 70
          max_critical_issues: 0
    
    config:
      max_concurrency: 3
      timeout: "30m"
      fail_fast: false
      retry_count: 1
      retry_delay: "10s"
      continue_on_error: false
      output_formats: ["console", "json"]
      reporting_config:
        include_details: true
        show_passed_checks: false
  
  quick:
    name: "Quick Health Check"
    description: "Fast health check for development"
    steps:
      - name: "git-checks"
        type: "checkers"
        enabled: true
        timeout: "1m"
        config:
          categories: ["git"]
      
      - name: "basic-reporting"
        type: "reporting"
        enabled: true
        timeout: "30s"
        dependencies: ["git-checks"]
        config:
          formats: ["console"]
    
    config:
      max_concurrency: 10
      timeout: "5m"
      fail_fast: true
      continue_on_error: true
      output_formats: ["console"]

# Conditional overrides based on repository characteristics
overrides:
  - name: "Java Projects"
    conditions:
      - type: "language"
        operator: "equals"
        value: "java"
    checkers:
      vulnerability-scan:
        enabled: true
        options:
          tool: "owasp-dependency-check"
  
  - name: "Large Repositories"
    conditions:
      - type: "repository"
        operator: "contains"
        value: "large"
    engine:
      repo_timeout: "20m"
      check_timeout: "5m"
  
  - name: "Legacy Projects"
    conditions:
      - type: "tag"
        operator: "in"
        values: ["legacy", "maintenance"]
    checkers:
      outdated-dependencies:
        enabled: false
      vulnerability-scan:
        options:
          severity_threshold: "high"

# Extensions configuration
extensions:
  plugins_dir: "./plugins"
  custom_checkers: []
  custom_analyzers: []
  custom_reporters: []

# Integration configurations
integrations:
  github:
    enabled: false
    token: "${GITHUB_TOKEN}"
    base_url: "https://api.github.com"
    options:
      create_issues: false
      update_pr_descriptions: false
  
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#health-checks"
    options:
      notify_on_failure: true
      notify_on_success: false
      include_summary: true
  
  jira:
    enabled: false
    url: "${JIRA_URL}"
    username: "${JIRA_USERNAME}"
    token: "${JIRA_TOKEN}"
    project: "HEALTH"
    options:
      create_tickets: false
      ticket_priority: "Medium"
      assignee: "health-bot"
