version: "1.0"

checkers:
  readme-check:
    enabled: true
    severity: medium
    timeout: 30s
    categories: ["documentation"]
    options:
      require_badges: true
      require_code_examples: true
      require_license_info: true
