version: "1.0"

engine:
  max_concurrency: 2
  timeout: 10m
  cache_enabled: true

checkers:
  git-status:
    enabled: true
    severity: medium
    timeout: 30s
    categories: ["git"]
    
  git-last-commit:
    enabled: false
    severity: low
    timeout: 30s
    categories: ["git"]
    
  vulnerability-scan:
    enabled: true
    severity: high
    timeout: 2m
    categories: ["security"]

analyzers:
  python:
    enabled: true
    file_extensions: [".py"]
    
  go:
    enabled: true
    file_extensions: [".go"]
