# Advanced Configuration Sample
# This file demonstrates the advanced configuration format with
# pipelines and comprehensive health checking options.

version: "1.0"

# Engine configuration with parallel execution support
engine:
  max_concurrency: 4
  timeout: 5m
  cache_enabled: true
  cache_ttl: 1h

# Modular checker configurations
checkers:
  git-status:
    enabled: true
    severity: medium
    timeout: 30s
    options:
      check_uncommitted: true
      check_unpushed: true
    categories: ["git"]

  git-commits:
    enabled: true
    severity: low
    timeout: 30s
    options:
      max_days_since_commit: 30
    categories: ["git"]

  dependencies-outdated:
    enabled: true
    severity: high
    timeout: 60s
    options:
      package_managers: ["npm", "pip", "go"]
      severity_threshold: "minor"
    categories: ["dependencies"]

  security-vulnerabilities:
    enabled: true
    severity: critical
    timeout: 120s
    options:
      scan_dependencies: true
      scan_code: false
    categories: ["security"]

  cyclomatic-complexity:
    enabled: true
    severity: medium
    timeout: 60s
    options:
      thresholds:
        python: 8
        java: 12
        go: 10
        javascript: 15
    categories: ["quality"]

  documentation-readme:
    enabled: true
    severity: low
    timeout: 30s
    options:
      min_length: 100
      require_sections: ["description", "installation", "usage"]
    categories: ["documentation"]

# Language analyzer configurations
analyzers:
  python:
    enabled: true
    file_extensions: [".py"]
    exclude_patterns: ["__pycache__", "*.pyc", ".venv"]
    complexity_enabled: true
    function_level: true
    categories: ["quality", "analysis"]

  go:
    enabled: true
    file_extensions: [".go"]
    exclude_patterns: ["vendor", "_test.go"]
    complexity_enabled: true
    function_level: true
    categories: ["quality", "analysis"]

  javascript:
    enabled: true
    file_extensions: [".js", ".jsx", ".ts", ".tsx"]
    exclude_patterns: ["node_modules", "dist", "build"]
    complexity_enabled: true
    function_level: false
    categories: ["quality", "analysis"]

  java:
    enabled: true
    file_extensions: [".java"]
    exclude_patterns: ["target", "*.class"]
    complexity_enabled: true
    function_level: true
    categories: ["quality", "analysis"]

# Reporter configurations
reporters:
  console:
    enabled: true
    template: table
    options:
      show_summary: true
      show_details: true
      color_output: true

  json:
    enabled: false
    output_file: "health-report.json"
    template: detailed
    options:
      pretty_print: true

  html:
    enabled: false
    output_file: "health-report.html"
    template: dashboard
    options:
      include_charts: true
      theme: "light"

# Category configurations for organizing checks
categories:
  git:
    name: "Git Health"
    description: "Git repository status and history checks"
    severity: medium
    enabled: true

  security:
    name: "Security Checks"
    description: "Security vulnerability and configuration checks"
    severity: critical
    enabled: true

  dependencies:
    name: "Dependency Management"
    description: "Dependency freshness and security checks"
    severity: high
    enabled: true

  quality:
    name: "Code Quality"
    description: "Code quality and complexity analysis"
    severity: medium
    enabled: true

  documentation:
    name: "Documentation"
    description: "Documentation quality and completeness checks"
    severity: low
    enabled: true

# Override configurations for specific repositories or conditions
overrides:
  - name: "legacy-repos"
    description: "Override for repositories not yet migrated"
    conditions:
      - type: "tag"
        field: "tags"
        operator: "contains"
        value: "legacy"
    checkers:
      security-vulnerabilities:
        enabled: false
        severity: critical
        timeout: 120s
        options:
          scan_dependencies: false
          scan_code: false
        categories: ["security"]
    analyzers: {}
    engine:
      max_concurrency: 1
      timeout: 10m
      cache_enabled: false

  - name: "javascript-projects"
    description: "Special configuration for JavaScript projects"
    conditions:
      - type: "language"
        field: "language"
        operator: "in"
        values: ["javascript", "typescript"]
    checkers:
      dependencies-outdated:
        enabled: true
        severity: high
        timeout: 60s
        options:
          package_managers: ["npm", "yarn"]
          severity_threshold: "minor"
        categories: ["dependencies"]
    analyzers:
      javascript:
        enabled: true
        file_extensions: [".js", ".jsx", ".ts", ".tsx"]
        exclude_patterns: ["node_modules", "dist", "build"]
        complexity_enabled: true
        function_level: true
    engine:

# Extension configurations (future use)
extensions:
  enabled: false
  plugins: []
  custom_checkers: []

# Integration configurations
integrations:
  github:
    enabled: false
    token: ""
    
  jira:
    enabled: false
    url: ""
    username: ""
    
  slack:
    enabled: false
    webhook_url: ""
