# Advanced Configuration Sample
# This file demonstrates the advanced configuration format with feature flags,
# profiles, and comprehensive health checking options.

version: "1.0"

# Feature flags for system control
feature_flags:
  - name: "modular_engine"
    enabled: true
    description: "Enable the modular execution engine"
  - name: "modular_checkers"
    enabled: true
    description: "Enable the modular checkers system"
  - name: "modular_analyzers"
    enabled: true
    description: "Enable the modular analyzers system"
  - name: "parallel_execution"
    enabled: true
    description: "Enable parallel execution of checks and analysis"
  - name: "advanced_config"
    enabled: true
    description: "Enable advanced configuration format support"
  - name: "legacy_compatibility"
    enabled: true
    description: "Enable legacy compatibility mode"
  - name: "config_migration"
    enabled: true
    description: "Enable automatic configuration migration"

# Engine configuration with parallel execution support
engine:
  max_concurrency: 4
  timeout: 5m
  cache_enabled: true
  cache_ttl: 1h

# Modular checker configurations
checkers:
  git-status:
    enabled: true
    severity: medium
    timeout: 30s
    options:
      check_uncommitted: true
      check_unpushed: true
    categories: ["git"]

  git-commits:
    enabled: true
    severity: low
    timeout: 30s
    options:
      max_days_since_commit: 30
    categories: ["git"]

  dependencies-outdated:
    enabled: true
    severity: high
    timeout: 60s
    options:
      package_managers: ["npm", "pip", "go"]
      severity_threshold: "minor"
    categories: ["dependencies"]

  security-vulnerabilities:
    enabled: true
    severity: critical
    timeout: 120s
    options:
      scan_dependencies: true
      scan_code: false
    categories: ["security"]

  cyclomatic-complexity:
    enabled: true
    severity: medium
    timeout: 60s
    options:
      thresholds:
        python: 8
        java: 12
        go: 10
        javascript: 15
    categories: ["quality"]

  documentation-readme:
    enabled: true
    severity: low
    timeout: 30s
    options:
      min_length: 100
      require_sections: ["description", "installation", "usage"]
    categories: ["documentation"]

# Language analyzer configurations
analyzers:
  python:
    enabled: true
    file_extensions: [".py"]
    exclude_patterns: ["__pycache__", "*.pyc", ".venv"]
    complexity_enabled: true
    function_level: true

  go:
    enabled: true
    file_extensions: [".go"]
    exclude_patterns: ["vendor", "_test.go"]
    complexity_enabled: true
    function_level: true

  javascript:
    enabled: true
    file_extensions: [".js", ".jsx", ".ts", ".tsx"]
    exclude_patterns: ["node_modules", "dist", "build"]
    complexity_enabled: true
    function_level: false

  java:
    enabled: true
    file_extensions: [".java"]
    exclude_patterns: ["target", "*.class"]
    complexity_enabled: true
    function_level: true

# Reporter configurations
reporters:
  console:
    enabled: true
    template: table
    options:
      show_summary: true
      show_details: true
      color_output: true

  json:
    enabled: false
    output_file: "health-report.json"
    template: detailed
    options:
      pretty_print: true

  html:
    enabled: false
    output_file: "health-report.html"
    template: dashboard
    options:
      include_charts: true
      theme: "light"

# Category configurations for organizing checks
categories:
  git:
    name: "Git Health"
    description: "Git repository status and history checks"
    severity: medium
    enabled: true

  security:
    name: "Security Checks"
    description: "Security vulnerability and configuration checks"
    severity: critical
    enabled: true

  dependencies:
    name: "Dependency Management"
    description: "Dependency freshness and security checks"
    severity: high
    enabled: true

  quality:
    name: "Code Quality"
    description: "Code quality and complexity analysis"
    severity: medium
    enabled: true

  documentation:
    name: "Documentation"
    description: "Documentation quality and completeness checks"
    severity: low
    enabled: true

# Execution profiles for different use cases
profiles:
  basic:
    name: "Basic Profile"
    description: "Essential checks for quick validation"
    checkers:
      git-status:
        enabled: true
        severity: medium
        timeout: 30s
        options:
          check_uncommitted: true
          check_unpushed: true
        categories: ["git"]
      git-commits:
        enabled: true
        severity: low
        timeout: 30s
        options:
          max_days_since_commit: 30
        categories: ["git"]
    analyzers: {}
    categories: ["git"]
    exclusions: []

  comprehensive:
    name: "Comprehensive Profile"
    description: "Enable all analyzers and advanced checks"
    checkers:
      git-status:
        enabled: true
        severity: medium
        timeout: 30s
        options:
          check_uncommitted: true
          check_unpushed: true
        categories: ["git"]
      git-commits:
        enabled: true
        severity: low
        timeout: 30s
        options:
          max_days_since_commit: 30
        categories: ["git"]
      cyclomatic-complexity:
        enabled: true
        severity: medium
        timeout: 60s
        options:
          thresholds:
            python: 8
            go: 10
        categories: ["quality"]
    analyzers:
      python:
        enabled: true
        file_extensions: [".py"]
        exclude_patterns: ["__pycache__", "*.pyc", ".venv"]
        complexity_enabled: true
        function_level: true
      go:
        enabled: true
        file_extensions: [".go"]
        exclude_patterns: ["vendor", "_test.go"]
        complexity_enabled: true
        function_level: true
    categories: ["git", "quality"]
    exclusions: []

  full-stack:
    name: "Full Stack Profile"
    description: "Complete health check suite with all components"
    checkers:
      git-status:
        enabled: true
        severity: medium
        timeout: 30s
        options:
          check_uncommitted: true
          check_unpushed: true
        categories: ["git"]
      git-commits:
        enabled: true
        severity: low
        timeout: 30s
        options:
          max_days_since_commit: 30
        categories: ["git"]
      dependencies-outdated:
        enabled: true
        severity: high
        timeout: 60s
        options:
          package_managers: ["npm", "pip", "go"]
          severity_threshold: "minor"
        categories: ["dependencies"]
      security-vulnerabilities:
        enabled: true
        severity: critical
        timeout: 120s
        options:
          scan_dependencies: true
          scan_code: false
        categories: ["security"]
      cyclomatic-complexity:
        enabled: true
        severity: medium
        timeout: 60s
        options:
          thresholds:
            python: 8
            java: 12
            go: 10
            javascript: 15
        categories: ["quality"]
      documentation-readme:
        enabled: true
        severity: low
        timeout: 30s
        options:
          min_length: 100
          require_sections: ["description", "installation", "usage"]
        categories: ["documentation"]
    analyzers:
      python:
        enabled: true
        file_extensions: [".py"]
        exclude_patterns: ["__pycache__", "*.pyc", ".venv"]
        complexity_enabled: true
        function_level: true
      go:
        enabled: true
        file_extensions: [".go"]
        exclude_patterns: ["vendor", "_test.go"]
        complexity_enabled: true
        function_level: true
      javascript:
        enabled: true
        file_extensions: [".js", ".jsx", ".ts", ".tsx"]
        exclude_patterns: ["node_modules", "dist", "build"]
        complexity_enabled: true
        function_level: false
      java:
        enabled: true
        file_extensions: [".java"]
        exclude_patterns: ["target", "*.class"]
        complexity_enabled: true
        function_level: true
    categories: ["git", "security", "dependencies", "quality", "documentation"]
    exclusions: []

  development:
    name: "Development Profile"
    description: "Fast checks for development workflow"
    checkers:
      git-status:
        enabled: true
        severity: medium
        timeout: 30s
        options:
          check_uncommitted: true
          check_unpushed: true
        categories: ["git"]
      cyclomatic-complexity:
        enabled: true
        severity: medium
        timeout: 60s
        options:
          thresholds:
            python: 8
            go: 10
        categories: ["quality"]
    analyzers:
      python:
        enabled: true
        file_extensions: [".py"]
        exclude_patterns: ["__pycache__", "*.pyc", ".venv"]
        complexity_enabled: true
        function_level: true
      go:
        enabled: true
        file_extensions: [".go"]
        exclude_patterns: ["vendor", "_test.go"]
        complexity_enabled: true
        function_level: true
    categories: ["git", "quality"]
    exclusions: []

  production:
    name: "Production Profile"
    description: "Comprehensive checks for production readiness"
    checkers:
      git-status:
        enabled: true
        severity: medium
        timeout: 30s
        options:
          check_uncommitted: true
          check_unpushed: true
        categories: ["git"]
      git-commits:
        enabled: true
        severity: low
        timeout: 30s
        options:
          max_days_since_commit: 30
        categories: ["git"]
      dependencies-outdated:
        enabled: true
        severity: high
        timeout: 60s
        options:
          package_managers: ["npm", "pip", "go"]
          severity_threshold: "minor"
        categories: ["dependencies"]
      security-vulnerabilities:
        enabled: true
        severity: critical
        timeout: 120s
        options:
          scan_dependencies: true
          scan_code: false
        categories: ["security"]
      cyclomatic-complexity:
        enabled: true
        severity: medium
        timeout: 60s
        options:
          thresholds:
            python: 8
            java: 12
            go: 10
            javascript: 15
        categories: ["quality"]
      documentation-readme:
        enabled: true
        severity: low
        timeout: 30s
        options:
          min_length: 100
          require_sections: ["description", "installation", "usage"]
        categories: ["documentation"]
    analyzers:
      python:
        enabled: true
        file_extensions: [".py"]
        exclude_patterns: ["__pycache__", "*.pyc", ".venv"]
        complexity_enabled: true
        function_level: true
      go:
        enabled: true
        file_extensions: [".go"]
        exclude_patterns: ["vendor", "_test.go"]
        complexity_enabled: true
        function_level: true
      javascript:
        enabled: true
        file_extensions: [".js", ".jsx", ".ts", ".tsx"]
        exclude_patterns: ["node_modules", "dist", "build"]
        complexity_enabled: true
        function_level: false
      java:
        enabled: true
        file_extensions: [".java"]
        exclude_patterns: ["target", "*.class"]
        complexity_enabled: true
        function_level: true
    categories: ["git", "security", "dependencies", "quality", "documentation"]
    exclusions: []

# Pipeline configurations for orchestrated execution
pipelines:
  standard:
    name: "Standard Health Check Pipeline"
    description: "Standard orchestrated health check workflow"
    steps:
      - name: "analysis"
        type: "analysis"
        enabled: true
        config:
          analyzers: ["python", "go"]
          parallel: true

      - name: "basic-checks"
        type: "checkers"
        enabled: true
        dependencies: ["analysis"]
        config:
          checkers: ["git-status", "git-commits"]
          fail_fast: false

      - name: "advanced-checks"
        type: "checkers"
        enabled: true
        dependencies: ["basic-checks"]
        config:
          checkers: ["dependencies-outdated", "cyclomatic-complexity"]
          parallel: true

      - name: "reporting"
        type: "reporting"
        enabled: true
        dependencies: ["advanced-checks"]
        config:
          reporters: ["console"]
          aggregate: true

    config:
      max_concurrency: 2
      timeout: "10m"
      fail_fast: false

  full-health-check:
    name: "Full Health Check Pipeline"
    description: "Comprehensive health check with all components"
    steps:
      - name: "preparation"
        type: "setup"
        enabled: true
        config:
          cache_cleanup: true
          log_level: "info"

      - name: "analysis"
        type: "analysis"
        enabled: true
        dependencies: ["preparation"]
        config:
          analyzers: ["python", "go", "javascript", "java"]
          parallel: true
          timeout: "5m"

      - name: "security-checks"
        type: "checkers"
        enabled: true
        dependencies: ["analysis"]
        config:
          checkers: ["security-vulnerabilities", "dependencies-outdated"]
          parallel: true
          timeout: "3m"

      - name: "quality-checks"
        type: "checkers"
        enabled: true
        dependencies: ["analysis"]
        config:
          checkers: ["cyclomatic-complexity", "documentation-readme"]
          parallel: true
          timeout: "2m"

      - name: "git-checks"
        type: "checkers"
        enabled: true
        config:
          checkers: ["git-status", "git-commits"]
          parallel: false
          timeout: "1m"

      - name: "final-reporting"
        type: "reporting"
        enabled: true
        dependencies: ["security-checks", "quality-checks", "git-checks"]
        config:
          reporters: ["console", "json"]
          aggregate: true
          summary: true

    config:
      max_concurrency: 4
      timeout: "15m"
      fail_fast: false

# Override configurations for specific repositories or conditions
overrides:
  - name: "legacy-repos"
    description: "Override for repositories not yet migrated"
    conditions:
      - type: "tag"
        field: "tags"
        operator: "contains"
        value: "legacy"
    checkers:
      security-vulnerabilities:
        enabled: false
        severity: critical
        timeout: 120s
        options:
          scan_dependencies: false
          scan_code: false
        categories: ["security"]
    analyzers: {}
    engine:
      max_concurrency: 1
      timeout: 10m
      cache_enabled: false

  - name: "javascript-projects"
    description: "Special configuration for JavaScript projects"
    conditions:
      - type: "language"
        field: "language"
        operator: "in"
        values: ["javascript", "typescript"]
    checkers:
      dependencies-outdated:
        enabled: true
        severity: high
        timeout: 60s
        options:
          package_managers: ["npm", "yarn"]
          severity_threshold: "minor"
        categories: ["dependencies"]
    analyzers:
      javascript:
        enabled: true
        file_extensions: [".js", ".jsx", ".ts", ".tsx"]
        exclude_patterns: ["node_modules", "dist", "build"]
        complexity_enabled: true
        function_level: true
    engine:

# Extension configurations (future use)
extensions:
  enabled: false
  plugins: []
  custom_checkers: []

# Integration configurations
integrations:
  github:
    enabled: false
    token: ""
    
  jira:
    enabled: false
    url: ""
    username: ""
    
  slack:
    enabled: false
    webhook_url: ""
