name: Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download Go dependencies
        run: go mod download

      - name: Install Go tools
        run: make install-go-tools

      - name: Verify Go build
        run: make build

      - name: Run code quality checks
        run: |
          make fmt
          make vet
          make lint

      - name: Run unit tests
        run: make test-unit

      - name: Run test coverage
        run: make test-coverage

      - name: Run integration tests
        run: make test-integration

      - name: Run benchmarks
        run: make test-bench

      - name: Build multi-platform binaries
        run: make build-all

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release