name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write # For OIDC token generation

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: production # Add environment protection
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5 # Updated to v5
        with:
          go-version: '1.24'
          cache: true # Enable Go module caching

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download Go dependencies
        run: go mod download

      - name: Debug git environment
        run: |
          git status
          git describe --tags --always --dirty || echo "git describe failed"
          git rev-parse --short HEAD || echo "git rev-parse failed"
          date -u +"%Y-%m-%d"

      - name: Verify Go build with debug
        run: |
          echo "Testing make variables:"
          make debug-vars
          make build
          echo "Testing binary version:"
          ./bin/repos version

      - name: Run code quality checks
        run: |
          make fmt
          make vet
          make lint

      - name: Run unit tests
        run: make test-unit

      - name: Run test coverage
        run: make test-coverage

      - name: Run integration tests
        run: make test-integration

      - name: Build multi-platform binaries
        run: |
          echo "Building multi-platform binaries with debug:"
          make debug-vars
          make build-all
          echo "Testing Linux binary version:"
          ./bin/repos-linux-amd64 version

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release